[package]
name = "test-output"
version = "0.8.0"
authors = ["PgBiel"]
edition = "2024"
license = "Apache-2.0"

[dependencies]
glistix-core = { path = "../compiler-core" }
glistix-cli = { path = "../compiler-cli" }
test-helpers-rs = { path = "../test-helpers-rs" }
camino = { workspace = true, features = ["serde1"] }

[dev-dependencies]
insta.workspace = true
