name: release-containers
on:
  release:
    types:
      - "published"

env:
  REGISTRY: ghcr.io

jobs:
  publish-container-images:
    name: publish-container-images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        base-image:
          - erlang
          - erlang-slim
          - erlang-alpine
          - elixir
          - elixir-slim
          - elixir-alpine
          - node
          - node-slim
          - node-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate with GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build version and tags
        id: versions
        run: |
          # Strip git ref prefix from version
          V_VERSION=$(echo "${{ github.ref }}" | sed -e 's|.*/\(.*\)|\1|')

          # Strip `v` prefix from version
          BARE_VERSION=$(echo "$V_VERSION" | sed -e 's|^v/\(.*\)|\1|')

          # Build version with platform
          PLATFORM_VERSION=$BARE_VERSION-${{ matrix.base-image }}

          # Build container tag
          TAG=$REGISTRY/${{ github.repository }}:$PLATFORM_VERSION

          echo "v_version=$V_VERSION" >> $GITHUB_OUTPUT
          echo "bare_version=$BARE_VERSION" >> $GITHUB_OUTPUT
          echo "platform_version=$PLATFORM_VERSION" >> $GITHUB_OUTPUT
          echo "container_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Download Glistix archive from GitHub release
        run: |
          VERSION=${{ steps.versions.outputs.v_version }}
          URL=https://github.com/${{ github.repository }}/releases/download/$VERSION/glistix-$VERSION-x86_64-unknown-linux-musl.tar.gz
          echo Downloading $URL
          curl -Lo glistix.tar.gz $URL

      - name: Unpack Glistix binary from archive
        run: tar xf glistix.tar.gz

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: containers/${{ matrix.base-image }}.dockerfile
          push: true
          tags: ${{ steps.versions.outputs.container_tag }}
          labels: |
            org.opencontainers.image.title=glistix
            org.opencontainers.image.url=https://github.com/Glistix/glistix
            org.opencontainers.image.source=https://github.com/Glistix/glistix
            org.opencontainers.image.version=${{ steps.versions.outputs.platform_version }}
            org.opencontainers.image.licenses=Apache-2.0
